config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :histories

  get 'users/sign_up', to: "users#new"
  post 'users', to: "users#create"
  get 'users/sign_in', to: 'sessions#new'

  resources :sessions, only: [:create, :destroy]

  root "histories#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ApplicationRecord
  mount_uploader :picture, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :histories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)
    @history.user = current_user
    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:title, :picture, :content, :remote_picture_url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    reset_session
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def create
    u = User.find_by(email: params[:user][:email]).try(:authenticate, params[:user][:password])
    if u.present?
      session[:user_id] = u.id
      redirect_to root_path
    else
      redirect_to users_sign_in_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_with(model: history, local: true, multipart: true, class: "form-horizontal") do |form| %>
  <% if history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <div class="form-group">
      <%= form.label :title, "Título", class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= form.text_field :title, id: :history_title, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :remote_picture_url, "URL Imagen", class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= image_tag(history.picture.thumb, style: "margin-bottom: 10px; border-radius: 5px;") if history.picture? %>

        <%= form.text_field :remote_picture_url, id: :history_picture, class: "form-control" %>
      </div>
      <%= form.hidden_field :picture_cache %>
    </div>

    <div class="form-group">
      <%= form.label :content, "Descripción", class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= form.text_area :content, id: :history_content, class: "form-control", rows: 10 %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= form.submit "Enviar", class: "btn btn-primary" %>
        <%= link_to 'Back', histories_path, class: "btn btn-default"  %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/histories/edit.html.erb
<legend>Editar Historia</legend>

<%= render 'form', history: @history %>

app/views/histories/index.html.erb
<div class="row">
  <div class="col-xs-8 col-sm-10 col-md-10">
    <h1>Histories</h1>
  </div>
  <div class="col-xs-4 col-sm-2 col-md-2">
    <%= link_to 'New History', new_history_path, class: "btn btn-info btn-sm" %>
  </div>
</div>

<div class="row">
  <% @histories.reverse.each do |history| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to(image_tag(history.picture.thumb), history) if history.picture? %>
        <div class="caption">
          <h3><%= history.title %></h3>
          <small><%= time_ago_in_words(history.created_at) %> ago</small>
          <p><%= history.content.truncate(150)  %></p>
          <p><%= link_to 'Show', history, class: "btn btn-primary" %> <%= link_to 'Edit', edit_history_path(history), class: "btn btn-warning" %> <%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>


<br>

app/views/histories/new.html.erb
<legend>Nueva Historia</legend>

<%= render 'form', history: @history %>

app/views/histories/show.html.erb
<div class="container">

      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <%= image_tag(@history.picture_url, style: "max-width: 100%; border-radius: 10px;") if @history.picture? %>
        </div>
        <div class="col-md-2"></div>
      </div>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <h1><%= @history.title %></h1>
          <small><%= time_ago_in_words(@history.created_at) %> ago</small>
        </div>
        <div class="col-md-2"></div>
      </div>

      <hr>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <p><%= @history.content %></p>
        </div>
        <div class="col-md-2"></div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-8"></div>
        <div class="col-md-2">
          <p><%= link_to 'Edit', edit_history_path(@history), class: "btn btn-warning btn-sm" %> <%= link_to 'Back', histories_path, class: "btn btn-info btn-sm" %></p>
        </div>
        <div class="col-md-2"></div>
      </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictory</title>
    <%= csrf_meta_tags %>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/3.4.1/united/bootstrap.min.css" rel="stylesheet" integrity="sha384-Sa176srEjCXftw8QYd+wY/WVLqUNOlQ+ENT4shhgMBfALErUsVL8RrhU4zWbWyRt" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <% if notice %>
        <div class="alert alert-dismissible alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4>Información</h4>
          <p><%= notice %></p>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-dismissible alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4>Atención</h4>
          <p><%= alert %></p>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Pictory</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= histories_path%>">Histories</a></li>
        <li><a href="#">Histories 2</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/new.html.erb
<h1>SIGN-UP</h1>

<%= form_with(model: @user) do |form| %>

 <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

   <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :user_email %>
  </div>

   <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <% end %>